name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 1' # Every Monday at midnight
  workflow_dispatch:

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit safety
        
    - name: Run Bandit security scan
      run: |
        bandit -r app/ -x app/tests/ -f json -o bandit-results.json
        
    - name: Check dependencies for vulnerabilities
      run: |
        safety check -r requirements.txt --output json > safety-results.json
        
    - name: Upload security scan results
      uses: actions/upload-artifact@v4
      with:
        name: security-scan-results
        path: |
          bandit-results.json
          safety-results.json
          
    - name: Fail if high severity issues found
      run: |
        if [ ! -s bandit-results.json ]; then
          echo "::warning::Empty bandit results file - security scan may have failed"
        elif grep -q '"severity": "high"' bandit-results.json; then
          echo "::error::High severity security issues found in code scan"
          exit 1
        else
          echo "No high severity issues found in security scan"
        fi
        
        if [ ! -s safety-results.json ]; then
          echo "::warning::Empty safety results file - dependency check may have failed"
        fi